### PR TITLE
Test conda environments for Linux and macOS

### LINKED ISSUE #37: SpecNotFound install error
On Mac OS, one user received the install error `SpecNotFound: Can't process without a name` when running `install_launch_mac.command`.  This was triggered by the line:
https://github.com/gitter-lab/ml-bio-workshop/blob/5abd3d40e0a562ae9d80efae1723ade73c4adb36/scripts/install_launch_mac.command#L11

This error is caused when the environment file does not exist https://github.com/conda/conda/issues/5681

### PR DESCRIPTION
**Pull request by agitter**
Closes #37

This pull request aims to test all three platforms' install scripts for the conda environments.

### CODE REVIEW

**Comment by agitter** [comment]
Testing the install script works for Linux and macOS if I edit the `ml4bio` command that launches the GUI and replace it with a command to check that the `ml4bio` package exists.

Windows still has problems.  The version of `sed` from [Chocolately](https://chocolatey.org/packages/sed) does not behave the same as in Linux.  In addition, the attempt to activate the environment and create it if it does not exist fails.  AppVeyor seems to fail on that error instead of letting the batch file continue to run.

**Comment by agitter** [comment]
The scope of this pull request has been reduced to only cover Linux and macOS.  #39 can track Windows testing issues.

**Comment by agitter** [comment]
@csmagnano @fmu2 I plan to merge this soon if there are no objections

**Comment by fmu2** [comment]
Sounds good.

**Comment by agitter** [comment]
@fmu2 thanks for fixing that error.  That will address #37.

**Pull request merged**
